[project]
name = "pythonfun"
version = "0.1.0"
description = "Add a short description here"
authors = ["Your Name <you@example.com>"]
channels = ["conda-forge"]
platforms = ["win-64"]

[tasks]

[dependencies]
pytest = ">=8.1.1,<8.2"
jupyter = ">=1.0.0,<1.1"
